<?php 
/*
Plugin Name: Link Whisper Bot
Plugin URI: http://realmdigital.io
Description: Extension for Link Whisper
Version: 0.0.1
Author: Benjamin Layton
Author URI: http://realmdigital.io
Text Domain: lwb
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}